### ISSUE TITLE
Cannot query historical balances on Kusama

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate-api-sidecar#634] opened 2021-08-12 14:03 UTC
I queried substrate-api-sidecar for historical account and it returned an error. My polkadot node is of the 0.9.8 release running kusama.

The query was:

`GET /accounts/{accountId}/balance-info?at=0x3361f6446c72aaa6679aa40a03e493a851161fd08cb53237968a9967902691c0`

The result was:

```
{
  "code": 500,
  "message": "Unable to decode storage system.account:: createType(AccountInfo):: {\"nonce\":\"Index\",\"refcount\":\"RefCount\",\"data\":\"AccountData\"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)",
  "stack": "Error: Unable to decode storage system.account:: createType(AccountInfo):: {\"nonce\":\"Index\",\"refcount\":\"RefCount\",\"data\":\"AccountData\"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)\n    at RpcCore._newType (/home/lilpep/dev/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:450:13)\n    at RpcCore._formatStorageData (/home/lilpep/dev/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:399:17)\n    at RpcCore._formatOutput (/home/lilpep/dev/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:376:19)\n    at callWithRegistry (/home/lilpep/dev/substrate-api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:255:42)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "level": "error"
}
```

Sidecar revision is: 5a3023b12a4282852afc039cf22b84f0f5207425

**Comment by TarikGul** [comment] 2021-08-12 14:13
Thanks for posting the issue. I was able to reproduce it, and got the same error as you mentioned above. Im gonna look into this right now.

```
{
  "code": 500,
  "message": "Unable to decode storage system.account:: createType(AccountInfo):: {\"nonce\":\"Index\",\"refcount\":\"RefCount\",\"data\":\"AccountData\"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)",
  "stack": "Error: Unable to decode storage system.account:: createType(AccountInfo):: {\"nonce\":\"Index\",\"refcount\":\"RefCount\",\"data\":\"AccountData\"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)\n    at RpcCore._newType (/Users/tarik/.nvm/versions/node/v14.15.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:450:13)\n    at RpcCore._formatStorageData (/Users/tarik/.nvm/versions/node/v14.15.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:399:17)\n    at RpcCore._formatOutput (/Users/tarik/.nvm/versions/node/v14.15.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:376:19)\n    at callWithRegistry (/Users/tarik/.nvm/versions/node/v14.15.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-core/bundle.cjs:255:42)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
  "level": "error"
}
```

**Comment by pepyakin** [comment] 2021-08-12 15:02
@shawntabrizi gave me a clue about this: this breakage may have something to do with a change of the storage key location for balances or account info.

**Comment by TarikGul** [comment] 2021-08-12 16:17
Yea that's interesting, thanks for the clue. I also created an issue in `@polkadot/api` to track this [here](https://github.com/polkadot-js/api/issues/3871).

**Comment by TarikGul** [comment] 2021-08-20 01:11
Hey @pepyakin, it should be resolved now via [#637](https://github.com/paritytech/substrate-api-sidecar/pull/637), most recent release v9.1.4 has the patch.

**Comment by TarikGul** [comment] 2021-08-31 16:57
Closing issue due to being resolved, please feel free to reopen if the issue arises

**Comment by TarikGul** [comment] 2021-09-01 18:27
Blocks under 1,500,000 are no longer returning errors but instead a balance of zero. Prematurely closed this issue.

**Closed** 2021-09-02 18:51 UTC
Labels: I2 - Bug 🐜, P2 - ASAP
