### ISSUE TITLE
Cannot read property 'validators' of undefined

### ISSUE THREAD

**Issue by tiendq** [paritytech/substrate-api-sidecar#743] opened 2021-11-01 07:01 UTC
**Description**

It has worked well for my local docker Moonbeam, but then fails with public testnet.

**Steps to Reproduce**

`NODE_ENV=production SAS_EXPRESS_BIND_HOST=0.0.0.0 SAS_EXPRESS_LOG_MODE=all SAS_LOG_LEVEL=http SAS_SUBSTRATE_WS_URL=wss://wss.testnet.moonbeam.network substrate-api-sidecar`

`curl http://localhost:8080/blocks/1053155 | jq` (this block here https://moonbase-blockscout.testnet.moonbeam.network/blocks/1053155/transactions)

**Expected vs. Actual Behavior**

I expected to get a block, instead got this error:

```
2021-10-29 11:28:21 error: Cannot read property 'validators' of undefined 
 TypeError: Cannot read property 'validators' of undefined
    at BlocksService.fetchBlock (/Users/tiendq/.nvm/versions/node/v14.17.0/lib/node_modules/@substrate/api-sidecar/build/src/services/blocks/BlocksService.js:45:39)
    at BlocksController.getBlockById (/Users/tiendq/.nvm/versions/node/v14.17.0/lib/node_modules/@substrate/api-sidecar/build/src/controllers/blocks/BlocksController.js:134:68)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Users/tiendq/.nvm/versions/node/v14.17.0/lib/node_modules/@substrate/api-sidecar/build/src/controllers/AbstractController.js:168:9
2021-10-29 11:28:21 error: GET /blocks/1053155 500 870ms
```

**Comment by tiendq** [comment] 2021-11-01 07:22
@TarikGul so how's about it this time? I can see the block in the explorer but failed to read it with sidecar.

**Comment by TarikGul** [comment] 2021-11-01 12:24
So the issue here is it's failing on not having the `session` module on moonbeam. Not super recently, but I had changed the way we query blocks from using api.derive to a stripped down version of the call. I query all the validators in order to get the author of the block. I am able to reproduce this so I will start looking for a sensible solution.

**Comment by TarikGul** [comment] 2021-11-01 12:27
Ahh okay so the reason it doesnt fail on the explorer is this line. https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/chain/getBlock.ts#L35

ill get a fix in asap. Thanks for reporting it

**Comment by TarikGul** [comment] 2021-11-01 19:26
@tiendq Fix is in, and will be in our next release on Wednesday.

**Closed** 2021-11-01 19:25 UTC
