### ISSUE TITLE
fis chain can not get fee

### ISSUE THREAD

**Issue by malingzhao** [paritytech/substrate-api-sidecar#1467] opened 2024-08-06 08:09 UTC
**Proposed Change or Idea**

[Describe your request for a new idea/feature or improvement of an existing
feature.]

**Alternatives**

[Are there alternative approaches or solutions that you’ve considered?]

**Additional Information**

[Add any other details about the feature request here.]

**Comment by HubDevi** [comment] 2024-08-07 14:31
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Regards.

**Comment by Imod7** [comment] 2024-08-07 14:52
Closing this issue as spam since it does not mention any problems or provide any information.

**Comment by Imod7** [comment] 2024-08-07 16:30
Reopening because of the title. Can you provide more info on the issue you are experiencing so I can try to reproduce ?

**Comment by Imod7** [comment] 2024-10-10 05:49
Closing as this is stale and no further input was provided. If you wish to re-open please provide more details and ways to reproduce the issue (chain you are connecting to, the endpoint you are querying and an example/test case of your query).

**Closed by Imod7** 2024-10-10 05:49 UTC
