### ISSUE TITLE
Unable to query dispatch info. error

### ISSUE THREAD

**Issue by paperfrog95** [paritytech/substrate-api-sidecar#1123] opened 2022-11-01 06:04 UTC
Hello, we are the company that develops coin wallet. 
Frequent errors when inquiring block information from sidecars.

We also communicate with the Polkadot team via Telegram.
Do sidecar also have telegram-like means of contact?
We collect all the blocks, so I think we can upload the information in real time if there is an error.

Env
- Sidecar : v14.0.1
-  Polkadot : v0.9.30
- Error block : 13128286 (WND) and etc.. 

Error Code
```
{
    "code": 500,
    "message": "1: Unable to query dispatch info.: Failed to decode return value of TransactionPaymentApi_query_info",
    "stack": "RpcError: 1: Unable to query dispatch info.: Failed to decode return value of TransactionPaymentApi_query_info\n    at checkError (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:34:11)\n    at RpcCoder.decodeResponse (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:54:5)\n    at WsProvider.value (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:297:90)\n    at W3CWebSocket.value [as onmessage] (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:277:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/src/app/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/usr/src/app/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/usr/src/app/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (node:events:527:28)\n    at WebSocketConnection.processFrame (/usr/src/app/node_modules/websocket/lib/WebSocketConnection.js:554:26)\n    at /usr/src/app/node_modules/websocket/lib/WebSocketConnection.js:323:40",
    "level": "error"
}
```

**Comment by niklasad1** [comment] 2022-11-01 08:45
Westend is running v9310 (it was updated last night https://westend.subscan.io/extrinsic/13128237-2) and if you read the release notes of sidecar v14.0.1 it is tested against v9300.

I think something was changed in the  `RuntimeDispatchInfo` in that release

/cc @marshacb

**Comment by paperfrog95** [comment] 2022-11-01 08:56
@niklasad1 Thank you, I have question.
After the coin chain version was released, I know Sidecar is testing that version.
What's the process on Real net(Polkadot)?
We're fine with having a test net failure.

**Comment by niklasad1** [comment] 2022-11-01 09:05
The release process works the following polkadot:

1. end of "pre-release" westend is upgraded
2. release polkadot version <x.y.z>
3. governance proposal runtime upgrade on kusama usually a week or something after the new binary has been released.
4. governance proposal runtime upgrade on polkadot usually a couple weeks after kusama has run the binary for a couple of weeks.

Thus, usually polkadot lags behind westend by two releases.

**Comment by IkerAlus** [comment] 2022-11-01 10:15
Other teams are reporting that this error happens when doing a call to `payment_queryInfo` on the root of the node/rpc endpoint so API Sidecar does not seem to be the root of the issue.

**Comment by wdstorer-bg** [comment] 2022-11-01 21:55
We are currently experiencing the same `TransactionPaymentApi_query_info` error since yesterday. Does this mean that there are no releases of the sidecar that are compatible with `westend` at the moment?

**Comment by IkerAlus** [comment] 2022-11-02 10:19
@wdstorer-bg As said before, the issue is out of the reach of API Sidecar application.

You can check [this Substrate Exchange post](https://substrate.stackexchange.com/questions/5634/rpc-payment-queryfeeinfo-fails-on-westend-9310) for more info on the nature of the issue.

**Comment by wdstorer-bg** [comment] 2022-11-02 13:43
@IkerAlus Thank you so much for the link :bow:

**Comment by karen-cb** [comment] 2022-11-02 22:11
If I understand correctly, the problem is that there is no new client release (i.e. v0.9.31) that is compatible with the current westend runtime v9310 to test sidecar against?

**Comment by IkerAlus** [comment] 2022-11-07 14:42
to add more context to the issue, this is the PR forSubstrate dealing with: https://github.com/paritytech/substrate/pull/12633

As recommended in that PR, most likely API Sidecar will switch to `state_call` to query the transaction info.

**Comment by TarikGul** [comment] 2022-11-22 00:18
I believe this is no longer an issue, and will close this for now. Please reopen an issue if this persists.

**Closed by TarikGul** 2022-11-22 00:18 UTC
