### ISSUE TITLE
Request timeouts and high memory usage

### ISSUE THREAD

**Issue by terorie** [paritytech/substrate-api-sidecar#368] opened 2020-12-18 15:16 UTC
**Description**

Version: v2.0.0

After letting the sidecar run for a few days and sending requests, memory usage accumulates to ~800 MB. CPU usage, disk I/O and file handle count metrics are all normal.

The API gets unresponsive and fails to serve requests. A call to `/blocks/head` takes over a minute and eventually aborts.

There are no log messages on the Polkadot node or sidecar that suggest any issues. 

After restarting the sidecar, memory usage drops to 100 MB and it serves requests immediately.

**Steps to Reproduce**

1. Deploy sidecar v2.0.0
2. Make requests for a few days

**Expected vs. Actual Behavior**

Quality of service should not degrade over time.

**Comment by emostov** [comment] 2020-12-18 17:12
Thank you for filing the issue with relevant details.

A few questions

1) What endpoints are you using?

2) Is Sidecar deployed in a container with anything else, like a Polkadot node?

3) Any guess if it is linked to the amount of time the service is up for or if it is more correlated to the quantity of requests?

**Comment by emostov** [comment] 2020-12-18 19:00
possibly related https://github.com/paritytech/substrate-api-sidecar/issues/363

**Comment by terorie** [comment] 2020-12-18 19:06
> 1. What endpoints are you using?
> 2. Is Sidecar deployed in a container with anything else, like a Polkadot node?
> 3. Any guess if it is linked to the amount of time the service is up for or if it is more correlated to the quantity of requests?

@emostov 

1. I'm mostly polling `/blocks/head` to construct a live update feed for transactions.
2. The sidecar is deployed on the same server as the Polkadot node.
3. Unfortunately not. Though I tried spamming the node with a few hundred requests and there was no noticeable difference in memory usage.

Sorry for filing such a superficial bug report, by the way. I don't have much more to share, and I'm trying to get more metrics myself to understand what's happening.

From alert logs on our clients, it looks like it takes about 3 days from startup until memory usage creeped up significantly. I think it's some sort of memory leak. And I feel like the memory consumption is related to overall response time, but that's just guessing.

With Go apps I would usually use `pprof` to get a heap dump and see what blocks long / takes large allocs. Would a coredump of the process help you, when the fault occurs again?

**Comment by terorie** [comment] 2020-12-18 19:07
@emostov #363 is related because it was filed by my colleague on the same node. I haven't seen the ticket. Sorry for the confusion!

**Comment by emostov** [comment] 2020-12-19 02:25
I did a quick check using an [old bench mark script](https://github.com/emostov/bench/blob/master/bench.sh) and [clinic doctor](https://clinicjs.org/doctor/). I ran it for about 5 minutes with a total request load of ~240 blocks with some breaks in between to see if memory allocation/usage usage declined (see script for details). Here are the results:

<img width="815" alt="Screen Shot 2020-12-18 at 5 51 30 PM" src="https://user-images.githubusercontent.com/32168567/102678185-b9cd4900-415b-11eb-9da1-48614facd607.png">


I set up sidecar in a gcp instance and am now running against [this script](https://github.com/emostov/bench/blob/master/bench_24.sh), which will run for at minimum 24 hours and will give me data from `clinic`. Hopefully I can replicate the problem to some degree and go from there.

> And I feel like the memory consumption is related to overall response time, but that's just guessing.

I have found that when making concurrent requests memory usage corresponds to response time. I think the Node event loop accumulates handles that only go away once the request life cycle finishes.

> ... I tried spamming the node with a few hundred requests and there was no noticeable difference in memory usage.

This is interesting - may be worth setting up a Sidecar instance with no traffic to see if there is any memory creep.

> The sidecar is deployed on the same server as the Polkadot node.

Would be great to make sure we can reproduce this Sidecar issue in an isolated enviroment to ensure it is not a memory leak from the polkadot node creeping.

> Would a coredump of the process help you, when the fault occurs again?

Getting some sort of memory snapshot right at failure sounds like the right track for tracking down an issue. If I was doing this locally I would use the node `--inspect` flag with the [google chrome dev memory profiling tool](https://developers.google.com/web/tools/chrome-devtools/memory-problems/heap-snapshots), but I am not sure how feasible this is for you. I will likely end up doing this on my end.

cc @danforbes this might be of interest to you

**Comment by emostov** [comment] 2020-12-19 22:20
I was not able to use clinic to monitor some overnight load tests because the tools seems to fail after awhile, but I was able to get a profile for about an hour with a pyramid style load test. I do not see anything concerning with memory usage.

<img width="1858" alt="Screen Shot 2020-12-19 at 2 18 26 PM" src="https://user-images.githubusercontent.com/32168567/102700749-2ea88d80-4205-11eb-9938-b4a84ed0e8d2.png">

**Comment by terorie** [comment] 2020-12-21 12:50
@emostov Thanks so much for the detailed testing, this helps a lot and looks similar to what I've seen.

I'm wondering, maybe is memory usage at 600 MB avg 1 GB peak expected, and my instance is just underprovisioned? If so the resource requirements should probably be mentioned in the docs to help people with capacity planning.

I don't want to upload the coredump here because it might contain sensitive information (environment variables, potential auth tokens and such). Can I reach you privately somehow? If I get the chance and there's an easy way with Docker, I'm going to run the `--inspect` flag also, good idea.

**Comment by terorie** [comment] 2020-12-21 13:04
> I have found that when making concurrent requests memory usage corresponds to response time. I think the Node event loop accumulates handles that only go away once the request life cycle finishes.

The high response time problem (>60s for /blocks/head) and (>500ms for /) occurred even when doing localhost curl requests at very slow rates (every 10 seconds or so). Maybe it might have actually come from the Polkadot node itself if the RPC interface took long to respond. FWIW I can rule out memory pressure since swap is disabled and we have aggressive OOM killer policy.

Since I last restarted the `sidecar-api` two days ago, memory usage has gone back up to 750 MB, like when it was slow. However, this time the Polkadot process takes up much less memory (1.5 GB now, ~4 GB previously). This is further indication that the Polkadot node might be responsible for the request timeouts. 

But again unfortunately I can't give enough information to reproduce. If possible, logging slow requests as warnings, as they get handled, would be useful.

**Comment by emostov** [comment] 2020-12-21 20:14
> I'm wondering, maybe is memory usage at 600 MB avg 1 GB peak expected, and my instance is just underprovisioned? If so the resource requirements should probably be mentioned in the docs to help people with capacity planning.

It looks to be the case that at least 600 MB avg is to be expected, but I will try and look further into.

> Can I reach you privately somehow? 

element: @zeke:matrix.parity.io, email: zeke@parity.io

> The high response time problem (>60s for /blocks/head) and (>500ms for /) occurred even when doing localhost curl requests at very slow rates (every 10 seconds or so). 
...
> Since I last restarted the sidecar-api two days ago, memory usage has gone back up to 750 MB, like when it was slow. However, this time the Polkadot process takes up much less memory (1.5 GB now, ~4 GB previously)

Is there any issue with the response time now that the Polkadot process is taking up much less memory?

**Comment by terorie** [comment] 2020-12-22 02:43
> Is there any issue with the response time now that the Polkadot process is taking up much less memory?

I left the most important part out 🤦🏻‍♂️ No, all queries return immediately without any delay, which is why I think it's more likely Polkadot has problems, than sidecar-api.

**Comment by terorie** [comment] 2020-12-28 13:05
Hey @emostov happy holidays, and good news, the supposed memory leak just happened again and I managed to grab a coredump 😄. Hopefully that can help with debugging. I sent you an email with a GDrive link from my `blockdaemon.com` email containing the coredump and `node` process used. 

Other things observed:
* This time the substrate-api-sidecar process had 2130 MB RES memory and Polkadot had 1863 MB RES memory.
* The sidecar responded instantly with a JSON error. It said `code: 500` and `message: unreachable`.
* After restarting the sidecar, it's back down to 100 MB RES and nolonger responds with this error.

**Comment by emostov** [comment] 2020-12-28 15:42
@terorie excellent, thank you! I can confirm receipt of the email(s). Hopefully I can take a close look in the next 24 hours.

**Comment by emostov** [comment] 2020-12-30 22:33
As an update I have spent a good bit of time poking through the core dump with `llnode`. I couldn't identify a single object or array that seemed to be getting super big, but there are definitely some interesting things I took notes on. I think the next step might be to create a branch instrumented with some memory usage logging. cc @dvdplm

**Comment by dvdplm** [comment] 2021-04-01 09:17
@terorie How are things looking on your end using 3.x and 4.x series of sidecar? Is memory leaks still a problem for you?

**Comment by terorie** [comment] 2021-04-02 13:03
@dvdplm Unfortunately, the issue was never fixed for us. The sidecar 2.x releases were unusable with the high memory usage and response time issues. The newer versions were not tested yet. Our backend was rewritten some time in January to use Polkadot's RPC endpoint directly. We did not observe any performance issues with this new backend.
Though I hope I can try out the latest sidecar 4.x release soon. Using Polkadot RPC from Golang is just horrible at the moment (because of SCALE encoding), so I'm looking forward to switching back to api-sidecar.

**Comment by dvdplm** [comment] 2021-04-12 13:13
> Though I hope I can try out the latest sidecar 4.x release soon.

Lovely, I hope this will sort out your issues. :)

> Using Polkadot RPC from Golang is just horrible at the moment (because of SCALE encoding)

Yeah, we're aware this is quite painful atm, apologies! There are plans to fix this, but it's not imminent. I think using sidecar is the best short/midterm solution.

**Comment by TarikGul** [comment] 2022-06-15 10:19
This has been slowly improved on via polkadot-js and sidecar overtime. We haven't seen this issue in a while so I am closing this for now. If this ever reoccurs or has similar issue feel free to reopen or create a new issue.

**Closed by TarikGul** 2022-06-15 10:19 UTC
Labels: I2 - Bug 🐜, P5 - Sometime Soon
