### ISSUE TITLE
/blocks/head endpoint always return "Cannot construct unknown type PolkadotPrimitivesV1SignedUncheckedSigned"

### ISSUE THREAD

**Issue by Notation** [paritytech/substrate-api-sidecar#787] opened 2021-12-07 11:40 UTC
**Description**

I'm running @substrate/api-sidecar of v11.3.2 as service of Kusama，it always return error when I call /blocks/head, just as below：

`createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding paraInherent.enter:: Struct: failed on args: Struct:: decodeU8a: failed at 0x1d03a0204600000000000000da21242e… on data:: decodeU8a: failed at 0x1d03a0204600000000000000da21242e… on bitfields: Vec<PolkadotPrimitivesV1SignedUncheckedSigned>:: decodeU8a: failed at 0xa0204600000000000000da21242e5132…:: DoNotConstruct: Cannot construct unknown type PolkadotPrimitivesV1SignedUncheckedSigned`

Am I using the wrong version or is there anything goes wrong?

**Steps to Reproduce**
@substrate/api-sidecar v11.3.2
polkadot 0.9.13-7d8f00b90c-x86_64-linux-gnu
endpoint /blocks/head
coin kusama

**Comment by TarikGul** [comment] 2021-12-07 11:41
@Notation , are you querying the node while it is syncing?

**Comment by Notation** [comment] 2021-12-07 11:55
> @Notation , are you querying the node while it is syncing?

The node is synced

**Comment by TarikGul** [comment] 2021-12-07 12:27
So currently with a blank slate of Sidecar, I am not able to reproduce this. I would make sure there are no conflicting version's or packages of sidecar, or peer deps such as `@polkadot/api` etc.

**Comment by FairyFromAlfeya** [comment] 2021-12-08 00:32
Have a similar issue

polkadot: 0.9.13
sidecar: 11.3.2

`{"code":500,"message":"Unable to decode storage session.validators:: createType(FrameSystemLimitsBlockLength):: DoNotConstruct: Cannot construct unknown type FrameSystemLimitsBlockLength","stack":"Error: Unable to decode storage session.validators:: createType(FrameSystemLimitsBlockLength):: DoNotConstruct: Cannot construct unknown type FrameSystemLimitsBlockLength\n    at RpcCore._newType (/usr/src/app/node_modules/@polkadot/rpc-core/bundle.cjs:477:13)\n    at RpcCore._formatStorageData (/usr/src/app/node_modules/@polkadot/rpc-core/bundle.cjs:422:17)\n    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/bundle.cjs:396:19)\n    at RpcCore._formatResult (/usr/src/app/node_modules/@polkadot/rpc-core/bundle.cjs:237:27)\n    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/bundle.cjs:261:19)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)","level":"error"}`

**Comment by Notation** [comment] 2021-12-08 09:08
> **Description**
> 
> I'm running @substrate/api-sidecar of v11.3.2 as service of Kusama，it always return error when I call /blocks/head, just as below：
> 
> `createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding paraInherent.enter:: Struct: failed on args: Struct:: decodeU8a: failed at 0x1d03a0204600000000000000da21242e… on data:: decodeU8a: failed at 0x1d03a0204600000000000000da21242e… on bitfields: Vec<PolkadotPrimitivesV1SignedUncheckedSigned>:: decodeU8a: failed at 0xa0204600000000000000da21242e5132…:: DoNotConstruct: Cannot construct unknown type PolkadotPrimitivesV1SignedUncheckedSigned`
> 
> Am I using the wrong version or is there anything goes wrong?
> 
> **Steps to Reproduce** @substrate/api-sidecar v11.3.2 polkadot 0.9.13-7d8f00b90c-x86_64-linux-gnu endpoint /blocks/head coin kusama

@substrate/api-sidecar v11.2.0 works fine @TarikGul @FairyFromAlfeya

**Comment by TarikGul** [comment] 2021-12-10 16:59
> @substrate/api-sidecar v11.2.0 works fine @TarikGul @FairyFromAlfeya

Awesome!

v11.3.3 was just recently released too, if you find yourself upgrading let me know if that poses any problems as well. I ended up polling `/blocks/head` for 24 hours against kusama, and didn't receive any errors in a "blank-slate" enviornment.

**Comment by TarikGul** [comment] 2021-12-13 14:34
Closing, using this [issue](https://github.com/paritytech/substrate-api-sidecar/issues/792) to track.

**Closed by TarikGul** 2021-12-13 14:34 UTC
