### ISSUE TITLE
GET /blocks/head fails on version 3.0.0 for polkadot 0.8.27

### ISSUE THREAD

**Issue by ngallagher** [paritytech/substrate-api-sidecar#409] opened 2021-02-01 00:22 UTC
I am pretty much running the latest on polkadot and the sidecar and I get the following faliure (it looks related to a recent fix).

```
{
code: 500,
message: "Cannot read property 'extrinsicBaseWeight' of undefined",
stack: "TypeError: Cannot read property 'extrinsicBaseWeight' of undefined at BlocksService.createCalcFee (/build/polkadot/sidecar/build/src/services/blocks/BlocksService.js:275:61) at BlocksService.fetchBlock (/build/polkadot/sidecar/build/src/services/blocks/BlocksService.js:85:63) at processTicksAndRejections (node:internal/process/task_queues:94:5) at async BlocksController.getLatestBlock (/build/polkadot/sidecar/build/src/controllers/blocks/BlocksController.js:102:49) at async /build/polkadot/sidecar/build/src/controllers/AbstractController.js:139:9",
level: "error"
}
```

I am using the following with --chain=westend

```
polkadot --version
polkadot 0.8.27-2f845699-x86_64-linux-gnu
```

GET /node/version

```
{
clientVersion: "0.8.27-2f845699-x86_64-linux-gnu",
clientImplName: "parity-westend",
chain: "Westend"
}
```

**Comment by ngallagher** [comment] 2021-02-01 00:24
I rolled back to 2.1.2 and saw a similar issue. JSON RPC works find for getting the last block.

**Comment by emostov** [comment] 2021-02-01 03:04
Hi @ngallagher - thank you for the detailed versioning info.

This error occurs with any version of api-sidecar before v2.1.2. 

There was a recent fix, as you allude to. You can see the specifics of the fix for the issue in this PR: https://github.com/paritytech/substrate-api-sidecar/pull/388. **tl;dr** the way an on chain constant used for fee calculation is stored changes in polkadot v0.8.27; we adjust to use the new constant for fee calculations when applicable.

I just doubled checked api-sidecar v3.0.0 against some blocks in Westend that include transactions (ex. #4189645) and cannot reproduce the issue.

Are you installing api-sidecar from the git repo or npm? 
If you are using the git repo my first guess might be that you need to run `yarn build` prior to running `yarn start` to ensure that the actual `.js` target files are inline with the `.ts`.

**Comment by ngallagher** [comment] 2021-02-01 10:32
I am building from the v3.0.0 tag after cloning the repo. Is there some way for me to confirm the build? Perhaps compare a checksum of some to a build artifact?

As the blocks progressed the error changed. I now see the following for GET /blocks/head

```
{
  "code": 500,
  "message": "Cannot read property 'map' of undefined",
  "stack": "TypeError: Cannot read property 'map' of undefined\n    at BlocksService.createCalcFee (/build/polkadot/sidecar/build/src/services/blocks/BlocksService.js:292:76)\n    at BlocksService.fetchBlock (/build/polkadot/sidecar/build/src/services/blocks/BlocksService.js:85:63)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async BlocksController.getLatestBlock (/build/polkadot/sidecar/build/src/controllers/blocks/BlocksController.js:102:49)\n    at async /build/polkadot/sidecar/build/src/controllers/AbstractController.js:139:9",
  "level": "error"
}
```
Referencing the following (cat -n) on the .js file.

```
   292              const coefficients = api.consts.transactionPayment.weightToFee.map((c) => {
   293                  return {
   294                      // Anything that could overflow Number.MAX_SAFE_INTEGER needs to be serialized
   295                      // to BigInt or string.
   296                      coeffInteger: c.coeffInteger.toString(10),
   297                      coeffFrac: c.coeffFrac.toNumber(),
   298                      degree: c.degree.toNumber(),
   299                      negative: c.negative,
   300                  };
   301              });
```

**Comment by ngallagher** [comment] 2021-02-01 11:00
At around block 3054080 it started to work, so older blocks seem to cause this issue? I have changed nothing, it just started to work.

**Comment by emostov** [comment] 2021-02-01 16:05
Do you have examples of exact block numbers that don't work?

**Comment by ngallagher** [comment] 2021-02-01 17:25
I have pruning set to about 10000 so the offending blocks are gone, but Id imagine anything around 2000000?

**Comment by emostov** [comment] 2021-02-04 00:52
I am still struggling to reproduce this issue. I would think it affects any older block with a signed transaction, but for example `blocks/1677259` on Westend works fine (https://westend.subscan.io/block/1677259) against v3.0.1.

**Comment by emostov** [comment] 2021-03-16 18:29
Closing due to inaactivity

**Closed by emostov** 2021-03-16 18:29 UTC
